version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=ls-pOfiHoPE-LiCi-9530-5849-xINuNudo1597
      - SERVICES=s3,codepipeline,codebuild,codedeploy
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"