name: Mi Pipeline CI/CD Final

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          # Ya no necesitamos poner "app/" porque está en la raíz
          pip install -r requirements.txt

      - name: Construir Imagen Docker
        run: |
          # El punto "." significa "busca el Dockerfile aquí mismo"
          docker build -t mi-app-web .